-- Analysis Engine Pro Concept Schema
-- Stores suggestions generated by LLMs or APIs

CREATE TABLE IF NOT EXISTS pro_suggestions (
  id TEXT PRIMARY KEY,
  snippet_id TEXT NOT NULL,
  start_index INTEGER,
  end_index INTEGER,
  suggestion_text TEXT NOT NULL,
  explanation TEXT,
  tone TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (snippet_id) REFERENCES captured_snippets(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pro_suggestions_snippet_id
  ON pro_suggestions(snippet_id);
